<?php

<?php
echo "<table style=\"display: inline-block; width: 250px; border: 1px solid #ccc; line-height: 110%; font-family: arial; font-size: 12px; margin: 1px;\">\n"; 
echo "<tbody>\n"; 
echo "<tr>\n"; 
echo "<td style=\"text-align: center; color: red; font-size: 13px; border-bottom: 1px #ccc solid;\"><b>HOTSPOT VOUCHER</b></td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>\n"; 
echo "<table style=\" text-align: center; width: 240px; background-color: #fff; line-height: 110%; font-size: 11px;\">\n"; 
echo "<tbody>\n"; 
echo "<tr style=\"background-color: #eee;\">\n"; 
echo "<td style=\"background-color: #fff; width: 33%\"><b>PLAN</b></td>\n"; 
echo "<td style=\"width: 33%\">Speed</td>\n"; 
echo "<td style=\"width: 33%\">Data</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td ><b>%u_actualProfileName%</b></td>\n"; 
echo "<td>Up to 1Mbps</td>\n"; 
echo "<td>%u_limitDownload%</td>\n"; 
echo "</tr>\n"; 
echo "</tbody>\n"; 
echo "</table>\n"; 
echo "</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>\n"; 
echo "<table style=\" text-align: center; width: 240px; background-color: #fff; line-height: 110%; font-size: 11px;\">\n"; 
echo "<tbody>\n"; 
echo "<tr style=\"background-color: #eee;\">\n"; 
echo "<td style=\"width: 33%\">Time Limit</td>\n"; 
echo "<td style=\"width: 33%\">Validity</td>\n"; 
echo "<td style=\"width: 33%\">Price</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>%u_limitUptime%</td>\n"; 
echo "<td>%u_timeLeft%</td>\n"; 
echo "<td>Rp %u_moneyPaid%</td>\n"; 
echo "</tr>\n"; 
echo "</tbody>\n"; 
echo "</table>\n"; 
echo "</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td>\n"; 
echo "<table style=\" text-align: center; width: 240px; background-color: #fff; line-height: 110%; font-size: 12px; border-top: 1px solid #ccc;\">\n"; 
echo "<tbody>\n"; 
echo "<tr style=\"color: red; font-size: 11px;\">\n"; 
echo "<td style=\"width: 50%\">Username</td>\n"; 
echo "<td>Password</td>\n"; 
echo "</tr>\n"; 
echo "<tr style=\"background-color: #fff;\">\n"; 
echo "<td style=\"color: #888; border: 1px #ccc solid;\">%u_username%</td>\n"; 
echo "<td style=\"color: #888; border: 1px #ccc solid;\">%u_password%</td>\n"; 
echo "</tr>\n"; 
echo "</tbody>\n"; 
echo "</table>\n"; 
echo "</td>\n"; 
echo "</tr>\n"; 
echo "<tr>\n"; 
echo "<td style=\"text-align: center; font-size:11px;\">Call: 082 324 660 655</td>\n"; 
echo "</tr>\n"; 
echo "</tbody>\n"; 
echo "</table>\n";
?>